// src/apiConfig.js
export const API_CONFIG = {
    "6": {
        "6A": "https://script.google.com/macros/s/AKfycbzY3pwIwlRHH0uVmljLgPWZFWTzBf3NIb-5ZdyphXeJESl0Kf-DdDzMrAh4Kyvvsp0nFw/exec",
        "6B1": "https://script.google.com/macros/s/AKfycbxxJ77bZXCCMZUINt6IBg5DDiqalkPxoATAY0PDqFDdr3ZiuWdn44kWF1nH8dR1sggC8w/exec",
        "6B2": "https://script.google.com/macros/s/AKfycbzpO58_bBnx4_7Pd6BeJxeHPDC7ym44Kulpg16Yd0anZURXB0X87qKJDj46g6IBZxNq/exec",
        "6C": "https://script.google.com/macros/s/AKfycbxJCqgASNLixWnT7L2SznQ95iqRU8wBSZpslAV8rUuui-C1BBRtTAdds184_jBHo7SfoQ/exec",
        "6D": "https://script.google.com/macros/s/AKfycbz0yo36cGLePUObM_1B6SwrhFAvfnaWd2aGTZHY5kRPHZI-BxqIX254dgGvzydP2k28/exec",
        "6E": "https://script.google.com/macros/s/AKfycbwtWTr4l43TzfyMIYusK1ghppz2V9XJztYe6MI3yAb6k7ObF4O0P7PUzBJdH9eLz0B0Aw/exec",
        "6F": "https://script.google.com/macros/s/AKfycbzFNL6xt6jmZrWpBGG976ZPfBL9Pr4H7xjrMm_Bz9SPWXbpXnlf57nWVkXrR4ZoGS4C/exec",
    },
    "7": {
        "7A": "https://script.google.com/macros/s/AKfycbxdzsNtneA4ZuVwvKdsUbWlIDv4_Uk3xHU2yd8GWWIbM7AGCWmWqCncCj1rtm_RpuN3/exec",
        "7B1": "https://script.google.com/macros/s/AKfycbxw6wNK7i26ZpUHa7pPnILqSvNJZBS8z7GgDz6DtuDxMvrAJdTaJCFIsH5Aoj_JdKSrcQ/exec",
        "7B2": "https://script.google.com/macros/s/AKfycbw25H6JLe7F9Myrvab2M86sMNyWmsgy45PsZqsam7rjRP1e2z495tpnc2eZ4ZF_UfYmfQ/exec",
        "7C": "https://script.google.com/macros/s/AKfycbzWAAct6ybF3OFEKZc5QI69mrat9iIvWvqGEKgz7noMpXgA1hT-Jq1GcYRVJe74QfWPxA/exec",
        "7D": "https://script.google.com/macros/s/AKfycbzFa42LvCKCkYBwbW9zBpnFpQVXznrt0fU3Yl4B3HLu0JeTrWq6Ggr7FwKqX4tSQK71Mw/exec",
        "7E": "https://script.google.com/macros/s/AKfycbx6_hk6CIIk9fHiSeHQNKUe7u-mVyBqsVuRxxRyj1pZYghMiO38G3jNXghgNqCJ3qR3/exec",
        "7F": "https://script.google.com/macros/s/AKfycbyZ_OQQe-NenA-O-la33gqvtM5hzfKsVLuLbvAtw0L-VbTa7HNKVxqC2qebs3i-c0PmpQ/exec",
    },
    "8": {
        "8A": "",
        "8B": "",
        "8C": "",
        "8D": "",
        "8E": "",
        "8F": "",
    },
    "9": {
        "9A": "",
        "9B": "",
        "9C": "",
        "9D": "",
        "9E": "",
        "9F": "",
    },
    "10": {
        "10A": "",
        "10B": "",
        "10C": "",
        "10D": "",
        "10E": "",
        "10F": "",
    },
    "11": {
        "11A": "",
        "11B": "https://script.google.com/macros/s/AKfycbwbSjY0SklVTTt4JvksAgyFSS0v_wV4QZIBgWPPaSryJQjPdfC3MQauy4MlN6SFwkxL/exec",
        "11C": "",
        "11D": "",
        "11E": "",
        "11F": "",
    },
    "12": {
        "12A": "",
        "12B": "",
        "12C": "",
        "12D": "",
        "12E": "",
        "12F": "",
    },
    "13": {
        "13A": "",
        "13B": "",
        "13C": "",
        "13D": "",
        "13E": "",
        "13F": "",
    }
};